# Generated by Django 5.2.10 on 2026-02-01 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_competition_deadline_and_more'),
        ('submissions', '0002_submission_cgpa_alter_submission_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField()),
                ('participant_1_name', models.CharField(max_length=100)),
                ('participant_1_roll', models.CharField(max_length=50)),
                ('participant_1_phone', models.CharField(max_length=15)),
                ('participant_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_2_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('participant_2_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('participant_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_3_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('participant_3_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('participant_4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_4_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('participant_4_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
