# Generated by Django 5.2.10 on 2026-02-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='deadline',
        ),
        migrations.AddField(
            model_name='competition',
            name='max_participants',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='competition',
            name='min_participants',
            field=models.IntegerField(default=1),
        ),
    ]
